cc_library (
  name = "hiredis-lib",
  srcs = [
    "deps/hiredis/async.c",
    "deps/hiredis/dict.c",
    "deps/hiredis/hiredis.c",
    "deps/hiredis/net.c",
    "deps/hiredis/read.c",
    "deps/hiredis/sds.c",
    "deps/hiredis/test.c",
    "deps/hiredis/async.h",
    "deps/hiredis/dict.h",
    "deps/hiredis/fmacros.h",
    "deps/hiredis/hiredis.h",
    "deps/hiredis/net.h",
    "deps/hiredis/read.h",
    "deps/hiredis/sds.h",
    "deps/hiredis/sdsalloc.h",
  ],
  hdrs = [
    "deps/hiredis/hiredis.h",
  ],
  copts = [
    "-Ideps/hiredis",
  ],
)

cc_library (
  name = "redis-server-lib",
  srcs = [
    "src/adlist.c",
    "src/ae.c",
    "src/anet.c",
    "src/aof.c",
    "src/bio.c",
    "src/bitops.c",
    "src/blocked.c",
    "src/childinfo.c",
    "src/cluster.c",
    "src/config.c",
    "src/crc16.c",
    "src/crc64.c",
    "src/db.c",
    "src/debug.c",
    "src/defrag.c",
    "src/dict.c",
    "src/endianconv.c",
    "src/evict.c",
    "src/expire.c",
    "src/geo.c",
    "src/geohash.c",
    "src/geohash_helper.c",
    "src/hyperloglog.c",
    "src/intset.c",
    "src/latency.c",
    "src/lazyfree.c",
    "src/lzf_c.c",
    "src/lzf_d.c",
    "src/memtest.c",
    "src/module.c",
    "src/multi.c",
    "src/networking.c",
    "src/notify.c",
    "src/object.c",
    "src/pqsort.c",
    "src/pubsub.c",
    "src/quicklist.c",
    "src/rand.c",
    "src/rax.c",
    "src/rdb.c",
    "src/redis-check-rdb.c",
    "src/release.c",
    "src/replication.c",
    "src/rio.c",
    "src/scripting.c",
    "src/sds.c",
    "src/sentinel.c",
    "src/server.c",
    "src/setproctitle.c",
    "src/sha1.c",
    "src/siphash.c",
    "src/slowlog.c",
    "src/sort.c",
    "src/sparkline.c",
    "src/syncio.c",
    "src/t_hash.c",
    "src/t_list.c",
    "src/t_set.c",
    "src/t_string.c",
    "src/t_zset.c",
    "src/util.c",
    "src/ziplist.c",
    "src/zipmap.c",
    "src/zmalloc.c",

    "src/adlist.h",
    "src/ae.h",
    "src/anet.h",
    "src/asciilogo.h",
    "src/atomicvar.h",
    "src/bio.h",
    "src/cluster.h",
    "src/config.h",
    "src/crc64.h",
    "src/debugmacro.h",
    "src/dict.h",
    "src/endianconv.h",
    "src/fmacros.h",
    "src/geo.h",
    "src/geohash.h",
    "src/geohash_helper.h",
    "src/help.h",
    "src/intset.h",
    "src/latency.h",
    "src/lzf.h",
    "src/lzfP.h",
    "src/pqsort.h",
    "src/quicklist.h",
    "src/rand.h",
    "src/rax.h",
    "src/rdb.h",
    "src/redisassert.h",
    "src/redismodule.h",
    "src/release.h",
    "src/rio.h",
    "src/sds.h",
    "src/sdsalloc.h",
    "src/server.h",
    "src/sha1.h",
    "src/slowlog.h",
    "src/solarisfixes.h",
    "src/testhelp.h",
    "src/util.h",
    "src/version.h",
    "src/ziplist.h",
    "src/zipmap.h",
    "src/zmalloc.h",
    "src/sparkline.h",
    "src/rax_malloc.h",
  ],
  deps = [
    ":hiredis-lib",
    ":lua-lib",
    ":linenoise-lib",
  ],
  copts = [
    "-Ideps/lua/src",
    "-Ideps/hiredis",
    "-DREDIS_STATIC=",
    "-std=c99 -pedantic",
  ],
)

cc_library (
  name = "lua-lib",
  srcs = [
    "deps/lua/src/fpconv.c",
    "deps/lua/src/lapi.c",
    "deps/lua/src/lauxlib.c",
    "deps/lua/src/lbaselib.c",
    "deps/lua/src/lcode.c",
    "deps/lua/src/ldblib.c",
    "deps/lua/src/ldebug.c",
    "deps/lua/src/ldo.c",
    "deps/lua/src/ldump.c",
    "deps/lua/src/lfunc.c",
    "deps/lua/src/lgc.c",
    "deps/lua/src/linit.c",
    "deps/lua/src/liolib.c",
    "deps/lua/src/llex.c",
    "deps/lua/src/lmathlib.c",
    "deps/lua/src/lmem.c",
    "deps/lua/src/loadlib.c",
    "deps/lua/src/lobject.c",
    "deps/lua/src/lopcodes.c",
    "deps/lua/src/loslib.c",
    "deps/lua/src/lparser.c",
    "deps/lua/src/lstate.c",
    "deps/lua/src/lstring.c",
    "deps/lua/src/lstrlib.c",
    "deps/lua/src/ltable.c",
    "deps/lua/src/ltablib.c",
    "deps/lua/src/ltm.c",
    "deps/lua/src/lua_bit.c",
    "deps/lua/src/lua_cjson.c",
    "deps/lua/src/lua_cmsgpack.c",
    "deps/lua/src/lua_struct.c",
    "deps/lua/src/lundump.c",
    "deps/lua/src/lvm.c",
    "deps/lua/src/lzio.c",
    "deps/lua/src/print.c",
    "deps/lua/src/strbuf.c",
    "deps/lua/src/fpconv.h",
    "deps/lua/src/lapi.h",
    "deps/lua/src/lauxlib.h",
    "deps/lua/src/lcode.h",
    "deps/lua/src/ldebug.h",
    "deps/lua/src/ldo.h",
    "deps/lua/src/lfunc.h",
    "deps/lua/src/lgc.h",
    "deps/lua/src/llex.h",
    "deps/lua/src/llimits.h",
    "deps/lua/src/lmem.h",
    "deps/lua/src/lobject.h",
    "deps/lua/src/lopcodes.h",
    "deps/lua/src/lparser.h",
    "deps/lua/src/lstate.h",
    "deps/lua/src/lstring.h",
    "deps/lua/src/ltable.h",
    "deps/lua/src/ltm.h",
    "deps/lua/src/lua.h",
    "deps/lua/src/luaconf.h",
    "deps/lua/src/lualib.h",
    "deps/lua/src/lundump.h",
    "deps/lua/src/lvm.h",
    "deps/lua/src/lzio.h",
    "deps/lua/src/strbuf.h",
    "src/solarisfixes.h",
  ],
  hdrs = [
    "deps/lua/src/lua.h",
  ],
)

cc_library(
  name = "linenoise-lib",
  srcs = [
    "deps/linenoise/linenoise.c",
  ],
  hdrs = [
    "deps/linenoise/linenoise.h",
  ],
)

cc_binary(
  name = "redis-server",
  srcs = [
    "src/server.c",
  ],
  deps = [
    ":redis-server-lib",
    ":lua-lib",
  ],
  copts = [
    "-Ideps/lua/src",
  ],
)

cc_binary(
  name = "redis-grpc",
  srcs = [
    "src/redis.grpc.pb.cc",
    "src/redis.grpc.pb.h",
    "src/redis.pb.cc",
    "src/redis.pb.h",
    "src/grpc-redis.cc",
  ],
  deps = [
    ":redis-server-lib",
    ":lua-lib",
  ],
  copts = [
    "-Ideps/lua/src",
  ],
)

cc_binary(
  name = "redis-benchmark",
  srcs = [
    "src/ae.c",
    "src/anet.c",
    "src/redis-benchmark.c",
    "src/adlist.c",
    "src/zmalloc.c",
    "src/adlist.h",
    "src/zmalloc.h",
    "src/fmacros.h",
    "src/anet.h",
    "src/config.h",
    "src/sds.h",
    "src/ae.h",
    "src/atomicvar.h",
  ],
  deps = [
    ":hiredis-lib",
  ],
  copts = [
    "-Ideps/hiredis",
  ],
)
